imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: security_access_control.yml }

framework:
    #esi:             ~
    default_locale:  "%locale%"
    translator:      { fallback: "%locale%" }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/../etc/routing.yml"
        strict_requirements: "%kernel.debug%"
    form:            true
    csrf_protection: true
    validation:      { enable_annotations: true }
    templating:      { engines: ['twig'] } #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trust_proxy_headers: false # Deprecated in 2.0; will be removed in 2.3 (used trusted_proxies instead)
    trusted_proxies: %framework.trusted_proxies%
    session:
      save_path:     "%kernel.cache_dir%/../sessions"

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

    globals:
        default_platform: %default_platform%
        platforms: %platforms%

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [ ]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        #closure:
        #    jar: "%kernel.root_dir%/Resources/java/compiler.jar"
        #yui_css:
        #    jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"

# Doctrine Configuration
doctrine:
    dbal:
        connections:
            default:
                driver:   "%db_connections.default.driver%"
                host:     "%db_connections.default.host%"
                port:     "%db_connections.default.port%"
                dbname:   "%db_connections.default.db_name%"
                user:     "%db_connections.default.user%"
                password: "%db_connections.default.password%"
                charset:  "%db_connections.default.charset%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer.transport%"
    host:      "%mailer.host%"
    username:  "%mailer.user%"
    password:  "%mailer.password%"
    spool:     { type: memory }

fos_user:
  db_driver:      orm
  firewall_name:  main
  user_class:     DreamHeaven\CoreBundle\Entity\User
  use_listener:   true

#  group:
#    group_class: DreamHeaven\CoreBundle\Entity\Group
#
#  service:
#    mailer:       %mailer.fos_user_mailer%

knp_menu:
  twig:
    template:       DreamHeavenAdminBundle:Shared:menu.html.twig

  templating:       false
  default_renderer: twig
