<?php

namespace DreamHeaven\AdminBundle\Controller\Security;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class SessionController__JMSInjector
{
    public static function inject($container) {
        $instance = new \DreamHeaven\AdminBundle\Controller\Security\SessionController();
        return $instance;
    }
}
