<?php

namespace DreamHeaven\AdminBundle\Controller\PlayerManagement;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class PlayerController__JMSInjector
{
    public static function inject($container) {
        $instance = new \DreamHeaven\AdminBundle\Controller\PlayerManagement\PlayerController();
        return $instance;
    }
}
