<?php

namespace DreamHeaven\AdminBundle\Controller\Settings;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class AccountController__JMSInjector
{
    public static function inject($container) {
        $instance = new \DreamHeaven\AdminBundle\Controller\Settings\AccountController();
        return $instance;
    }
}
