<?php

namespace DreamHeaven\AdminBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class ImpersonatorController__JMSInjector
{
    public static function inject($container) {
        $instance = new \DreamHeaven\AdminBundle\Controller\ImpersonatorController();
        return $instance;
    }
}
