<?php

namespace DreamHeaven\AdminBundle\Controller\GameMaster;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class GroupManagementController__JMSInjector
{
    public static function inject($container) {
        $instance = new \DreamHeaven\AdminBundle\Controller\GameMaster\GroupManagementController();
        return $instance;
    }
}
