<?php

namespace DreamHeaven\AdminBundle\Controller\GameManagement;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class LoginAnnouncementController__JMSInjector
{
    public static function inject($container) {
        $instance = new \DreamHeaven\AdminBundle\Controller\GameManagement\LoginAnnouncementController();
        return $instance;
    }
}
