<?php

namespace Lianz\SimpleFormBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class SimpleFormDemoController__JMSInjector
{
    public static function inject($container) {
        $instance = new \Lianz\SimpleFormBundle\Controller\SimpleFormDemoController();
        return $instance;
    }
}
